name: E2E tests (Supabase)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        # Build needs Supabase env vars available at build-time because the
        # app imports the Supabase client during server-side module evaluation.
        run: npm run build

      - name: Start server (production build) with Supabase secrets
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        # start in background
        run: npm run start &

      - name: Wait for server
        run: npx wait-on http://localhost:3000 --timeout 120000

      - name: Run Cypress (headless)
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: npx cypress run --spec "cypress/e2e/**/*.cy.ts"

      - name: Upload Cypress videos and screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-screenshots
          path: |
            cypress/videos/**
            cypress/screenshots/**
